### ISSUE TITLE
Which Fivem version do I need for this server template?

### ISSUE THREAD

**Issue by yusuf57rl** [bitpredator/empiretown#189]
Finished pulling Docker container image
:/home/container$ $(pwd)/alpine/opt/cfx-server/ld-musl-x86_64.so.1 --library-path "$(pwd)/alpine/usr/lib/v8/:$(pwd)/alpine/lib/:$(pwd)/alpine/usr/lib/" -- $(pwd)/alpine/opt/cfx-server/FXServer +set citizen_dir $(pwd)/alpine/opt/cfx-server/citizen/ +set sv_licenseKey ${FIVEM_LICENSE} +set steam_webApiKey ${STEAM_WEBAPIKEY} +set sv_maxplayers ${MAX_PLAYERS} +set serverProfile default +set txAdminPort ${TXADMIN_PORT} $( [ "$TXADMIN_ENABLE" == "1" ] || printf %s '+exec server.cfg' )
/entrypoint.sh: line 13: /home/container/alpine/opt/cfx-server/ld-musl-x86_64.so.1: No such file or directory

**Comment by bitpredator** [comment]
Hi, this is a ready to use server you can follow the wiki to install the server correctly (I recommend installing the "main" version to have the latest updates). It is recommended to use the "Windows Server" operating system for the proper functioning of the server. Server Artifacts are already entered. The fivem version to use is the latest available through automatic updates
