### ISSUE TITLE
shaking screen like Bombs going off 

### ISSUE THREAD

**Issue by oakieville** [bitpredator/empiretown#192]
I think this more an issue with this pc or mistake made in install though ive reinstalled afew times now however when playing on the server the screen keeps bouncing/shaking like explosions are going off around me but none are. I installed on second pc and it i was able to run it however im not able to run the included fxserver.exe i get a error i have to use an older fxserver perhaps i dont correct  runtime installed not sure as i have many installed . if anyone has An idea or expeirenced similar pkease chime in

**Comment by bitpredator** [comment]
Hello, can you provide me with a screenshot or a short video of the problems you are having, also I would like to know which version of the server you have installed and if you have followed my installation procedure provided in the wiki.

**Comment by oakieville** [comment]
sorry for the delayed response i did follow the instructions  not sure what i did wrong or what the issue is in removed it reinstalled and same issue it but i did same procedure on second pc and it works fine. Possible its the pc but most likeky i simple made an error myself as i am completely new to rp server and have tons to learn

**Comment by bitpredator** [comment]
Hello, I'm glad that the problem has been solved in such a short time, if you encounter other problems or have new suggestions to improve this "FRAMEWORK" feel free to let me know.

The problem was solved by: @oakieville 

Greetings @bitpredator
