### ISSUE TITLE
[Bug] - "yarn" - Compile EasyAdmin +  script waiting to load

### ISSUE THREAD

**Issue by GlobalKiller666** [bitpredator/empiretown#203]
Hello, recently i instaled your fivem empiretown server files.
All is ok but server console shows me error:
script:yarn] yarn is currently busy: we are waiting to compile EasyAdmin
Can you help me to solve this error?

![Untitled](https://user-images.githubusercontent.com/127791100/224821547-37028760-d7b6-4a36-94e5-15748d0905ad.jpg)

Also cant login into server.

![Untitled2](https://user-images.githubusercontent.com/127791100/224824363-c1ec9b0b-75bc-42ea-8fe2-5b756a8acca2.jpg)

**Comment by bitpredator** [comment]
Hello @GlobalKiller666 , can you share your.log file so that we can solve the problem immediately

**Comment by bitpredator** [comment]
Thanks @GlobalKiller666 , I'll check and let you know shortly

**Comment by bitpredator** [comment]
I think I solved your problem, kindly you can use the "main" version and keep me updated on your problem :)

**Comment by GlobalKiller666** [comment]
Its in progress, but its still in awaiting scripts.
[fxserver.log](https://github.com/bitpredator/empiretown/files/10962373/fxserver.log)

**Comment by bitpredator** [comment]
Can you kindly upload CitizenFX_log

**Comment by GlobalKiller666** [comment]
cant find it, where it should be?

**Comment by bitpredator** [comment]
the path should look like this:
C:\Users\utente\AppData\Local\FiveM\FiveM.app\logs

**Comment by GlobalKiller666** [comment]
[CitizenFX_log_2023-03-13T225323.log](https://github.com/bitpredator/empiretown/files/10962534/CitizenFX_log_2023-03-13T225323.log)

last one?

**Comment by bitpredator** [comment]
yes, this is it

**Comment by bitpredator** [comment]
@GlobalKiller666 
The problem in "waiting for script" seems to be a bad connection (configuration) to your database.
If you wish, I can install the server and database via remote desktop.

**Comment by GlobalKiller666** [comment]
can we contact tomorrow?
Do you have skype? discord?

**Comment by bitpredator** [comment]
Unfortunately no sorry, I don't use discord or skype. You can still contact me in this thread whenever you want, the time slots in which you can find me are from 21:30 UTC until approximately 00:00.
