### ISSUE TITLE
Guns

### ISSUE THREAD

**Issue by oakieville** [bitpredator/empiretown#234]
This is probable not where i shouldput this so sorry if its wrong as this isnt sn issue its my lack of knowledge about this but how do i use guns in empiretown

**Comment by bitpredator** [comment]
Hi @oakieville , in Empiretown there is an advanced crafting system which means that the gunsmith will have to make the weapons and ammunition through the raw materials available in prepared places (remember that each weapon uses ammunition of different caliber as in real life) .

**Comment by oakieville** [comment]
Ty so much i did not realize that i was thinking i could add them through in tge database but i will read up on how tge crafting system works and try to figure it out if you happen to have know any good links to read please let me know if not ty very much for the fast reply

**Comment by bitpredator** [comment]
The crafting system looks like this: https://www.youtube.com/watch?v=P5ewpCkYo3s
(remember crafting locations and raw materials are different)

**Comment by oakieville** [comment]
Awesome ty very much

**Comment by bitpredator** [comment]
happy to have helped you

**Comment by bitpredator** [comment]
Hi @oakieville , I'll close this issue as completed, I've created a special thread to get to know Empiretown better, in case of need feel free to write in the thread or open a problem if you find it.

Discussion links: https://github.com/bitpredator/empiretown/discussions/242

Best regards @bitpredator
