### ISSUE TITLE
Cant Select Job Showing On Begining

### ISSUE THREAD

**Issue by LievreAI** [bitpredator/empiretown#305]
i cant select job in the begin of the spawn after create account it show nothing then unemployed

**Comment by bitpredator** [comment]
Hi @LievreAI , all the jobs have been configured as whitelist, if you want to make some of them no whitelist you will have to edit the "jobs" column inside the database
Example: ('taxi', 'Taxi', 0),
to make it no whitelist

**Comment by LievreAI** [comment]
i cant choose any job service , i want to be EMS and my friend police however its not working 
i try changed in the spawn point which you start the game to get my work service but the only thing i see is the unemployed
when that not working i try to open the database , and changed the job inside the user instant of unemployed to police or EMS not working too

**Comment by LievreAI** [comment]
Solved

**Comment by bitpredator** [comment]
After changing the database remember to restart the whole server.

**Comment by LievreAI** [comment]
allright , i also wonder about weapon in the police station

**Comment by bitpredator** [comment]
the server uses a weapon crafting system through the work of the gunsmith, if you wish you can give yourself weapons through the command
"giveitem (your id) WEAPON_PISTOL50 1"

you will also have to give yourself the ammo through the command "giveitem (your id) ammo-50 250"
