### ISSUE TITLE
change the server lang to english

### ISSUE THREAD

**Issue by LievreAI** [bitpredator/empiretown#307]
kind new to this sorry , how i can put the server in english

**Comment by bitpredator** [comment]
Hi, replace string 16 of your server.cfg with this one " sets locale "en-EN" "

**Comment by LievreAI** [comment]
well after doing that its bring me cute error 
SCRIPT ERROR: @bpt_vehicletax/server/server.lua:14: No such export getSharedObject in resource es_extended

for the protocol i using the latest version of fxserver

**Comment by bitpredator** [comment]
> well after doing that its bring me cute error SCRIPT ERROR: @bpt_vehicletax/server/server.lua:14: No such export getSharedObject in resource es_extended
> 
> for the protocol i using the latest version of fxserver


I will check this issue

**Comment by LievreAI** [comment]
@bitpredator the error still exist
![Screenshot 2023-04-12 232343](https://user-images.githubusercontent.com/84988313/231576120-bb210925-6009-49d6-b3ba-3b353873b415.png)

**Comment by bitpredator** [comment]
> @bitpredator the error still exist ![Screenshot 2023-04-12 232343](https://user-images.githubusercontent.com/84988313/231576120-bb210925-6009-49d6-b3ba-3b353873b415.png)

Can you provide information on how to reproduce this problem

**Comment by bitpredator** [comment]
> well after doing that its bring me cute error SCRIPT ERROR: @bpt_vehicletax/server/server.lua:14: No such export getSharedObject in resource es_extended
> 
> for the protocol i using the latest version of fxserver


Resolved #308

**Comment by LievreAI** [comment]
cool !!! work
