### ISSUE TITLE
SQL error while uploading

### ISSUE THREAD

**Issue by TheFury4** [bitpredator/empiretown#377]
Error

SQL query: Copy

-- Dump dei dati della tabella es_extended.npwd_twitter_tweets: ~0 rows (circa)

-- Dump della struttura di tabella es_extended.owned_vehicles
CREATE TABLE IF NOT EXISTS `owned_vehicles` (
  `owner` varchar(46) DEFAULT NULL,
  `plate` varchar(12) NOT NULL,
  `vehicle` longtext DEFAULT NULL,
  `type` varchar(20) NOT NULL DEFAULT 'car',
  `job` varchar(20) DEFAULT NULL,
  `stored` tinyint(4) NOT NULL DEFAULT 0,
  `parking` varchar(60) DEFAULT NULL,
  `pound` varchar(60) DEFAULT NULL,
  `trunk` longtext DEFAULT NULL,
  `glovebox` longtext DEFAULT NULL,
  `peopleWithKeys` longtext DEFAULT '[]',
  `mileage` float DEFAULT 0,
  PRIMARY KEY (`plate`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

MySQL said: Documentation
#1101 - BLOB, TEXT, GEOMETRY or JSON column 'peopleWithKeys' can't have a default value

**Comment by bitpredator** [comment]
Hi @TheFury4 I will check this problem as soon as possible

**Comment by bitpredator** [comment]
I just released a database fix, please let me know if this update worked, Thanks for reporting the issue.
