### ISSUE TITLE
[BUG] es_extended was unable to query + crafting_level' has no default value

### ISSUE THREAD

**Issue by Bennii9595** [bitpredator/empiretown#614]
[      script:oxmysql] Error: es_extended was unable to execute a query!
[      script:oxmysql] Query: INSERT INTO `users` SET `accounts` = ?, `identifier` = ?, `group` = ?, `firstname` = ?, `lastname` = ?, `dateofbirth` = ?, `sex` = ?, `height` = ?
[      script:oxmysql] Field 'crafting_level' doesn't have a default value

**Comment by bitpredator** [comment]
Hi, are you using the "main" version or others?

Can you provide me with information on how to reproduce the reported problem.

**Comment by Bennii9595** [comment]
the latest version

**Comment by bitpredator** [comment]
Hi, can you try using the "main" version? and let me know if the problem persists.

**Comment by Bennii9595** [comment]
no matter what version it not work i cannot even enter the server

**Comment by Bennii9595** [comment]
it say account created have fun butnot load the game

**Comment by Bennii9595** [comment]
or should i install esx legacy before?

**Comment by bitpredator** [comment]
esx legacy, it is not absolutely necessary for the functioning of empiretown, in fact it would only cause conflict problems. You need to install https://github.com/bitpredator/cfx-server-data ;

On my site you can find the server and database installation guide https://bitpredator.github.io/bptdevelopment/docs/empiretown/install-server

**Comment by Bennii9595** [comment]
[    c-scripting-core] Creating script environments for esx-radio
[    script:esx-radio] SCRIPT ERROR: @esx-radio/server.lua:2: No such export addChannelCheck in resource pma-voice
[           resources] Started resource esx-radio
[    c-scripting-core] Creating script environments for screenshot-basic
[           resources] Started resource screenshot-basic
[    c-scripting-core] Creating script environments for pma-voice
[           resources] Started resource pma-voice
[    c-scripting-core] Creating script environments for npwd
[           resources] Started resource npwd
[    c-scripting-core] Creating script environments for npwd_services
[           resources] Started resource npwd_services
[                 cmd] Argument count mismatch (passed 3, wanted 2)
[         script:yarn] [yarn]	yarn install v1.22.5
[         script:yarn] info No lockfile found.
[         script:yarn] [1/4] Resolving packages...
[         script:yarn] Error: [yarn]	warning Resolution field "@discordjs/util@0.3.1" is incompatible with requested version "@discordjs/util@.2.0"
[      script:oxmysql] [10.3.39-MariaDB-0+deb10u1] Database server connection established!
[         script:npwd] Error: Unhandled promise failure: Error: 
[         script:npwd] ==============================================
[         script:npwd] 
[         script:npwd] !!! NPWD WAS UNABLE TO VALIDATE YOUR DATABASE AND FINISH STARTING !!!
[         script:npwd] 
[         script:npwd] Player table is missing required columns: [phone_number]
[         script:npwd] 
[         script:npwd] This error is most likely caused by incorrect values in the config.json file.
[         script:npwd] 
[         script:npwd] ==============================================
[         script:npwd]     at fatalDbError (@npwd/dist/game/server/server.js:57847:9)
[         script:npwd]     at _BootService.validateDatabaseSchema (@npwd/dist/game/server/server.js:57888:7)
[         script:npwd]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[         script:npwd]     at async _BootService.handleResourceStarting (@npwd/dist/game/server/server.js:57874:5)
[         script:npwd]     at async @npwd/dist/game/server/server.js:57931:5
[         script:npwd]     at async citizen:/scripting/v8/main.js:482:9
[script:esx_vehiclesh] SCRIPT ERROR: @esx_vehicleshop/server/main.lua:26: esx_vehicleshop was unable to execute a query!
[script:esx_vehiclesh] Query: SELECT * FROM vehicle_categories
[script:esx_vehiclesh] []
[script:esx_vehiclesh] Table 'ESXLegacy_AC0EA9.vehicle_categories' doesn't exist
[script:esx_vehiclesh] > SQLVehiclesAndCategories (@esx_vehicleshop/server/main.lua:26)
[script:esx_vehiclesh] > handler (@esx_vehicleshop/server/main.lua:21)
[script:esx_vehiclesh] > printError (@oxmysql/dist/build.js:24891)
[script:esx_vehiclesh] > rawQuery (@oxmysql/dist/build.js:25065)
[script:esx_vehiclesh] > processTicksAndRejections (node:internal/process/task_queues:96)
[      script:oxmysql] Error: esx_boat was unable to execute a query!
[      script:oxmysql] Query: UPDATE owned_vehicles SET `stored` = true WHERE `stored` = false AND type = ?
[      script:oxmysql] ["boat"]
[      script:oxmysql] Table 'ESXLegacy_AC0EA9.owned_vehicles' doesn't exist
[script:bpt_vehicleta] SCRIPT ERROR: @bpt_vehicletax/server/server.lua:6: bpt_vehicletax was unable to execute a query!
[script:bpt_vehicleta] Query: SELECT * FROM vehicles
[script:bpt_vehicleta] []
[script:bpt_vehicleta] Table 'ESXLegacy_AC0EA9.vehicles' doesn't exist
[script:bpt_vehicleta] > cb (@bpt_vehicletax/server/server.lua:6)
[script:bpt_vehicleta] > onReady (@oxmysql/lib/MySQL.lua:127)
[script:bpt_vehicleta] > fn (@oxmysql/lib/MySQL.lua:134)
[script:bpt_vehicleta] > printError (@oxmysql/dist/build.js:24891)
[script:bpt_vehicleta] > rawQuery (@oxmysql/dist/build.js:25065)
[script:bpt_vehicleta] > processTicksAndRejections (node:internal/process/task_queues:96)
[  script:es_extended] [WARNING] Ignoring job grades for police due to missing job
[  script:es_extended] [WARNING] Ignoring job grades for police due to missing job
[  script:es_extended] [WARNING] Ignoring job grades for police due to missing job
[  script:es_extended] [WARNING] Ignoring job grades for police due to missing job
[  script:es_extended] [WARNING] Ignoring job grades for police due to missing job
[  script:es_extended] [WARNING] Ignoring job grades for cardealer due to missing job
[  script:es_extended] [WARNING] Ignoring job grades for cardealer due to missing job
[  script:es_extended] [WARNING] Ignoring job grades for cardealer due to missing job
[  script:es_extended] [WARNING] Ignoring job grades for cardealer due to missing job
[  script:es_extended] [WARNING] Ignoring job grades for ambulance due to missing job
[  script:es_extended] [WARNING] Ignoring job grades for ambulance due to missing job
[  script:es_extended] [WARNING] Ignoring job grades for ambulance due to missing job
[  script:es_extended] [WARNING] Ignoring job grades for ambulance due to missing job
[  script:es_extended] [WARNING] Ignoring job grades for mechanic due to missing job
[  script:es_extended] [WARNING] Ignoring job grades for mechanic due to missing job
[  script:es_extended] [WARNING] Ignoring job grades for mechanic due to missing job
[  script:es_extended] [WARNING] Ignoring job grades for mechanic due to missing job
[  script:es_extended] [WARNING] Ignoring job grades for mechanic due to missing job
[  script:es_extended] [WARNING] Ignoring job grades for taxi due to missing job
[  script:es_extended] [WARNING] Ignoring job grades for taxi due to missing job
[  script:es_extended] [WARNING] Ignoring job grades for taxi due to missing job
[  script:es_extended] [WARNING] Ignoring job grades for taxi due to missing job
[  script:es_extended] [WARNING] Ignoring job grades for taxi due to missing job
[  script:es_extended] [WARNING] Ignoring job grades for import due to missing job
[  script:es_extended] [WARNING] Ignoring job grades for import due to missing job
[  script:es_extended] [WARNING] Ignoring job grades for import due to missing job
[  script:es_extended] [WARNING] Ignoring job grades for import due to missing job
[  script:es_extended] [WARNING] Ignoring job grades for import due to missing job
[  script:es_extended] [WARNING] Ignoring job grades for ammu due to missing job
[  script:es_extended] [WARNING] Ignoring job grades for ammu due to missing job
[  script:es_extended] [WARNING] Ignoring job grades for ammu due to missing job
[  script:es_extended] [WARNING] Ignoring job grades for ammu due to missing job
[  script:es_extended] [WARNING] Ignoring job grades for ammu due to missing job
[  script:es_extended] [WARNING] Ignoring job grades for dustman due to missing job
[  script:es_extended] [WARNING] Ignoring job grades for dustman due to missing job
[  script:es_extended] [WARNING] Ignoring job grades for dustman due to missing job
[  script:es_extended] [WARNING] Ignoring job grades for dustman due to missing job
[  script:es_extended] [WARNING] Ignoring job grades for dustman due to missing job
[  script:es_extended] [WARNING] Ignoring job grades for ballas due to missing job
[  script:es_extended] [WARNING] Ignoring job grades for ballas due to missing job
[  script:es_extended] [WARNING] Ignoring job grades for ballas due to missing job
[  script:es_extended] [WARNING] Ignoring job grades for ballas due to missing job
[  script:es_extended] [WARNING] Ignoring job grades for ballas due to missing job
[  script:es_extended] [WARNING] Ignoring job grades for baker due to missing job
[  script:es_extended] [WARNING] Ignoring job grades for baker due to missing job
[  script:es_extended] [WARNING] Ignoring job grades for baker due to missing job
[  script:es_extended] [WARNING] Ignoring job grades for baker due to missing job
[  script:es_extended] [WARNING] Ignoring job grades for baker due to missing job
[  script:es_extended] [WARNING] Ignoring job grades for unicorn due to missing job
[  script:es_extended] [WARNING] Ignoring job grades for unicorn due to missing job
[  script:es_extended] [WARNING] Ignoring job grades for unicorn due to missing job
[  script:es_extended] [WARNING] Ignoring job grades for unicorn due to missing job
[  script:es_extended] [WARNING] Ignoring job grades for unicorn due to missing job
[  script:es_extended] [WARNING] Ignoring job grades for delivery due to missing job
[  script:es_extended] [WARNING] Ignoring job grades for driving due to missing job
[  script:es_extended] [WARNING] Ignoring job grades for driving due to missing job
[  script:es_extended] [WARNING] Ignoring job grades for driving due to missing job
[  script:es_extended] [WARNING] Ignoring job grades for driving due to missing job
[  script:es_extended] [WARNING] Ignoring job grades for driving due to missing job
[  script:es_extended] [INFO] BPT FRAMEWORK INITIALIZED
[      script:oxmysql] 2 2
[      script:oxmysql] 7 7
[      script:oxmysql] 4 7
[      script:oxmysql] An update is available for oxmysql (current version: 2.7.4)
[      script:oxmysql] https://github.com/overextended/oxmysql/releases/tag/v2.7.7
[       script:ox_lib] An update is available for ox_lib (current version: 3.9.0)
[       script:ox_lib] https://github.com/overextended/ox_lib/releases/tag/v3.16.2
[  script:esx_society] SCRIPT ERROR: @esx_society/server/main.lua:24: attempt to index a nil value (field '?')
[  script:esx_society] > handler (@esx_society/server/main.lua:24)
[  script:esx_society] > rawQuery (@oxmysql/dist/build.js:25056)
[  script:esx_society] > processTicksAndRejections (node:internal/process/task_queues:96)
[ script:ox_inventory] SCRIPT ERROR: @ox_inventory/modules/mysql/server.lua:81: ox_inventory was unable to execute a query!
[ script:ox_inventory] Query: SHOW COLUMNS FROM `owned_vehicles`
[ script:ox_inventory] []
[ script:ox_inventory] Table 'ESXLegacy_AC0EA9.owned_vehicles' doesn't exist
[ script:ox_inventory] > fn (@ox_inventory/modules/mysql/server.lua:81)
[ script:ox_inventory] > printError (@oxmysql/dist/build.js:24891)
[ script:ox_inventory] > rawQuery (@oxmysql/dist/build.js:25065)
[ script:ox_inventory] > processTicksAndRejections (node:internal/process/task_queues:96)
[script:esx_multichar] [INFO] Updated 2 columns to use VARCHAR(46)
[ citizen-server-impl]         fff                          
[ citizen-server-impl]   cccc ff   xx  xx     rr rr    eee  
[ citizen-server-impl] cc     ffff   xx       rrr  r ee   e 
[ citizen-server-impl] cc     ff     xx   ... rr     eeeee  
[ citizen-server-impl]  ccccc ff   xx  xx ... rr      eeeee 
[ citizen-server-impl]                                      
[ citizen-server-impl] Authenticated with cfx.re Nucleus: https://bennis-channel-v8b8qk.users.cfx.re/
[       script:ox_lib] An update is available for ox_doorlock (current version: 1.14.1)
[       script:ox_lib] https://github.com/overextended/ox_doorlock/releases/tag/v1.14.4
[         script:yarn] Error: [yarn]	warning Resolution field "@discordjs/rest@1.6.0" is incompatible with requested version "@discordjs/rest@.7.1"
[         script:yarn] Error: [yarn]	warning Resolution field "@discordjs/ws@0.8.1" is incompatible with requested version "@discordjs/ws@.8.2"
[script:esx_uteknark1] [21:06:28] <esx_uteknark1> Product item in configuration (coke) found in ESX: Good!
[script:esx_uteknark1] [21:06:28] <esx_uteknark1> Seed item in configuration (coke_seed) found in ESX: Good!
[      script:oxmysql] Error: esx_uteknark1 was unable to execute a query!
[      script:oxmysql] Query: SELECT `id`, `stage`, UNIX_TIMESTAMP(`time`) AS `time`, `x`, `y`, `z`, `soil` FROM `uteknark1`;
[      script:oxmysql] []
[      script:oxmysql] Table 'ESXLegacy_AC0EA9.uteknark1' doesn't exist
[ script:ox_inventory] [info] Inventory has loaded 260 items
[ script:esx_property] [INFO] Adding Property into datastore table
[ script:esx_property] [INFO] Adding last_property column to users table
[ script:esx_property] [INFO] Adding Property into datastore_data table
[         script:yarn] Error: [yarn]	warning Resolution field "@discordjs/rest@1.6.0" is incompatible with requested version "@discordjs/rest@.7.0"
[         script:yarn] Error: [yarn]	warning Resolution field "@discordjs/util@0.3.1" is incompatible with requested version "@discordjs/util@.2.0"
[         script:yarn] Error: [yarn]	warning Resolution field "@discordjs/builders@1.6.3" is incompatible with requested version "@discordjs/builders@.6.4"
[         script:yarn] Error: [yarn]	warning Resolution field "@discordjs/collection@1.5.1" is incompatible with requested version "@discordjs/collection@.5.2"
[         script:yarn] Error: [yarn]	warning Resolution field "@discordjs/rest@1.6.0" is incompatible with requested version "@discordjs/rest@.0.0"
[         script:yarn] warning Resolution field "@discordjs/util@0.3.1" is incompatible with requested version "@discordjs/util@.0.0"
[         script:yarn] warning Resolution field "@discordjs/ws@0.8.1" is incompatible with requested version "@discordjs/ws@.0.0"
[         script:yarn] Error: [yarn]	warning Resolution field "@discordjs/util@0.3.1" is incompatible with requested version "@discordjs/util@.2.0"
[         script:yarn] Error: [yarn]	warning Resolution field "@discordjs/ws@0.8.1" is incompatible with requested version "@discordjs/ws@.8.2"
[         script:yarn] [yarn]	[2/4] Fetching packages...
[         script:yarn] Error: [yarn]	error @sapphire/shapeshift@3.9.6: The engine "node" is incompatible with this module. Expected version ">=v18". Got "16.9.1"
[         script:yarn] Error: [yarn]	error Found incompatible module.
[         script:yarn] [yarn]	info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
[ citizen-server-impl] Building resource EasyAdmin failed.
[ citizen-server-impl] Error data: yarn failed!
> txaReportResources
[      script:monitor] [txAdmin] Sending resources list to txAdmin.
[  script:es_extended] Connecting: benjaminmani28
[script:esx_multichar] SCRIPT ERROR: @esx_multicharacter/server/main.lua:64: esx_multicharacter was unable to execute a query!
[script:esx_multichar] Query: SELECT identifier, accounts, job, job_grade, firstname, lastname, dateofbirth, sex, skin, disabled FROM users WHERE identifier LIKE ? LIMIT ?
[script:esx_multichar] ["char%:75f051b25f976b3bf93355bdc4f564c394063946",4]
[script:esx_multichar] Unknown column 'firstname' in 'field list'
[script:esx_multichar] > SetupCharacters (@esx_multicharacter/server/main.lua:64)
[script:esx_multichar] > handler (@esx_multicharacter/server/main.lua:200)
[script:esx_multichar] > printError (@oxmysql/dist/build.js:24891)
[script:esx_multichar] > rawQuery (@oxmysql/dist/build.js:25065)
[script:esx_multichar] > processTicksAndRejections (node:internal/process/task_queues:96)

**Comment by bitpredator** [comment]
EasyAdmin is no longer supported by Empiretown, also many problems I see here in the list have been resolved, I will do a clean install of the "main" server and will let you know as soon as possible.

**Comment by bitpredator** [comment]
Hi, I just released a new version fixing various issues, let me know if everything works correctly, (make sure to update your database).

https://github.com/bitpredator/empiretown/releases/tag/1.0.0

Greetings Bitpredator

**Comment by Bennii9595** [comment]
[           resources] Scanning resources.
[   resources:.github] Warning: .github does not have a resource manifest (fxmanifest.lua)
[           resources] Found 113 resources.
[           resources] 1 warning was encountered.
[          svadhesive] Authenticating server license key...
[          svadhesive] Server license key authentication succeeded. Welcome!
[    c-scripting-core] Creating script environments for sessionmanager
[           resources] Started resource sessionmanager
[    c-scripting-core] Creating script environments for monitor
[      script:monitor] [txAdmin] Resource v6.0.2 threads and commands set up. All Ready.
[           resources] Started resource monitor
[    c-scripting-core] Creating script environments for yarn
[           resources] Started resource yarn
[    c-scripting-core] Creating script environments for webpack
[           resources] Started resource webpack
[    c-scripting-core] Creating script environments for chat
[           resources] Started resource chat
[           resources] Started resource spawnmanager
[           resources] Started resource chat-theme-gtao
[    c-scripting-core] Creating script environments for oxmysql
[           resources] Started resource oxmysql
[    c-scripting-core] Creating script environments for es_extended
[           resources] Started resource es_extended
[    c-scripting-core] Creating script environments for ox_lib
[           resources] Started resource ox_lib
[    c-scripting-core] Creating script environments for esx_context
[           resources] Started resource esx_context
[    c-scripting-core] Creating script environments for esx_identity
[           resources] Started resource esx_identity
[           resources] Started resource esx_menu_default
[           resources] Started resource esx_menu_dialog
[           resources] Started resource esx_menu_list
[    c-scripting-core] Creating script environments for fivem-appearance
[           resources] Started resource fivem-appearance
[    c-scripting-core] Creating script environments for esx_multicharacter
[           resources] Started resource esx_multicharacter
[    c-scripting-core] Creating script environments for esx_notify
[           resources] Started resource esx_notify
[    c-scripting-core] Creating script environments for esx_progressbar
[           resources] Started resource esx_progressbar
[    c-scripting-core] Creating script environments for esx_addonaccount
[           resources] Started resource esx_addonaccount
[    c-scripting-core] Creating script environments for esx_society
[           resources] Started resource esx_society
[    c-scripting-core] Creating script environments for esx_textui
[           resources] Started resource esx_textui
[           resources] Started resource mythic_notify
[           resources] Started resource rprogress
[    c-scripting-core] Creating script environments for BOBsHunt
[           resources] Started resource BOBsHunt
[    c-scripting-core] Creating script environments for jsfour-idcard
[           resources] Started resource jsfour-idcard
[    c-scripting-core] Creating script environments for BasicItem
[           resources] Started resource BasicItem
[    c-scripting-core] Creating script environments for esx-qalle-jail
[           resources] Started resource esx-qalle-jail
[    c-scripting-core] Creating script environments for esx-radialmenu
[           resources] Started resource esx-radialmenu
[    c-scripting-core] Creating script environments for esx_RealisticVehicleFailure
[           resources] Started resource esx_RealisticVehicleFailure
[    c-scripting-core] Creating script environments for esx_addoninventory
[           resources] Started resource esx_addoninventory
[    c-scripting-core] Creating script environments for esx_ambulancejob
[           resources] Started resource esx_ambulancejob
[    c-scripting-core] Creating script environments for esx_banking
[           resources] Started resource esx_banking
[    c-scripting-core] Creating script environments for esx_status
[           resources] Started resource esx_status
[    c-scripting-core] Creating script environments for esx_basicneeds
[           resources] Started resource esx_basicneeds
[    c-scripting-core] Creating script environments for esx_billing
[           resources] Started resource esx_billing
[    c-scripting-core] Creating script environments for esx_vehicleshop
[           resources] Started resource esx_vehicleshop
[    c-scripting-core] Creating script environments for esx_boat
[           resources] Started resource esx_boat
[    c-scripting-core] Creating script environments for esx_datastore
[           resources] Started resource esx_datastore
[    c-scripting-core] Creating script environments for esx_license
[           resources] Started resource esx_license
[    c-scripting-core] Creating script environments for esx_dmvschool
[resources:esx_dmvsch] Warning: could not find server_script `server/main.lua` (defined in fxmanifest.lua:13)
[           resources] Started resource esx_dmvschool (1 warning)
[    c-scripting-core] Creating script environments for esx_garage
[           resources] Started resource esx_garage
[    c-scripting-core] Creating script environments for esx_holdup
[           resources] Started resource esx_holdup
[    c-scripting-core] Creating script environments for esx_joblisting
[           resources] Started resource esx_joblisting
[    c-scripting-core] Creating script environments for esx_lscustom
[           resources] Started resource esx_lscustom
[    c-scripting-core] Creating script environments for esx_mechanicjob
[           resources] Started resource esx_mechanicjob
[    c-scripting-core] Creating script environments for esx_policejob
[           resources] Started resource esx_policejob
[    c-scripting-core] Creating script environments for esx_property
[           resources] Started resource esx_property
[    c-scripting-core] Creating script environments for esx_rpchat
[           resources] Started resource esx_rpchat
[    c-scripting-core] Creating script environments for esx_taxijob
[           resources] Started resource esx_taxijob
[    c-scripting-core] Creating script environments for esx_uteknark1
[           resources] Started resource esx_uteknark1
[    c-scripting-core] Creating script environments for wk_wars2x
[           resources] Started resource wk_wars2x
[    c-scripting-core] Creating script environments for bpt_ammujob
[           resources] Started resource bpt_ammujob
[    c-scripting-core] Creating script environments for bpt_bakerjob
[           resources] Started resource bpt_bakerjob
[    c-scripting-core] Creating script environments for bpt_ballasjob
[           resources] Started resource bpt_ballasjob
[    c-scripting-core] Creating script environments for bpt_crafting
[           resources] Started resource bpt_crafting
[    c-scripting-core] Creating script environments for bpt_deliveries
[           resources] Started resource bpt_deliveries
[    c-scripting-core] Creating script environments for bpt_doorlock
[resources:bpt_doorlo] Warning: could not find server_script `server/convert.lua` (defined in fxmanifest.lua:25)
[resources:bpt_doorlo] Warning: could not find server_script `server/framework/*.lua` (defined in fxmanifest.lua:25)
[resources:bpt_doorlo] Warning: could not find server_script `server/main.lua` (defined in fxmanifest.lua:25)
[           resources] Started resource bpt_doorlock (3 warnings)
[    c-scripting-core] Creating script environments for bpt_dustman
[           resources] Started resource bpt_dustman
[    c-scripting-core] Creating script environments for bpt_farmer
[           resources] Started resource bpt_farmer
[    c-scripting-core] Creating script environments for bpt_fisherman
[           resources] Started resource bpt_fisherman
[    c-scripting-core] Creating script environments for bpt_hud
[           resources] Started resource bpt_hud
[    c-scripting-core] Creating script environments for bpt_importjob
[           resources] Started resource bpt_importjob
[           resources] Started resource bpt_loadscreen
[    c-scripting-core] Creating script environments for bpt_lumberjack
[           resources] Started resource bpt_lumberjack
[    c-scripting-core] Creating script environments for bpt_menu
[           resources] Started resource bpt_menu
[    c-scripting-core] Creating script environments for bpt_streetfight
[           resources] Started resource bpt_streetfight
[    c-scripting-core] Creating script environments for bpt_teleport
[           resources] Started resource bpt_teleport
[    c-scripting-core] Creating script environments for bpt_unicornjob
[           resources] Started resource bpt_unicornjob
[    c-scripting-core] Creating script environments for bpt_vehicletax
[           resources] Started resource bpt_vehicletax
[    c-scripting-core] Creating script environments for bpt_wallet
[           resources] Started resource bpt_wallet
[resources:pack_cars:] Asset pack_cars/p911r.ytd uses 36.2 MiB of physical memory.
[           resources] Started resource pack_cars (1 warning)
[           resources] Started resource tagt3flat6
[    c-scripting-core] Creating script environments for ox_inventory
[           resources] Started resource ox_inventory
[    c-scripting-core] Creating script environments for ox_fuel
[           resources] Started resource ox_fuel
[    c-scripting-core] Creating script environments for wasabi_backpack
[           resources] Started resource wasabi_backpack
[    c-scripting-core] Creating script environments for wasabi_fishing
[           resources] Started resource wasabi_fishing
[    c-scripting-core] Creating script environments for wasabi_mining
[           resources] Started resource wasabi_mining
[    c-scripting-core] Creating script environments for wasabi_oxshops
[           resources] Started resource wasabi_oxshops
[           resources] Started resource CayoTwoIslands
[           resources] Started resource SLBK11_MissionRow
[           resources] Started resource WarehousePort
[           resources] Started resource bob74_ipl
[resources:cityhallv4] Asset cityhallv4/qt_sg_mesh_doorframes.ydr uses 30.8 MiB of virtual memory.
[resources:cityhallv4] Asset cityhallv4/tex_qt_low_gover_only_sec_prop_high.ytd uses 24.0 MiB of physical memory.
[           resources] Started resource cityhallv4 (2 warnings)
[resources:gabzemsv2:] Asset gabzemsv2/gabz_pillbox_textures_01.ytd uses 27.5 MiB of physical memory.
[           resources] Started resource gabzemsv2 (1 warning)
[           resources] Started resource gcom_ballas_gang
[           resources] Started resource hdigitalden
[           resources] Started resource iak_ammunation
[           resources] Started resource import
[           resources] Started resource pablito_restauracja
[           resources] Started resource patoche_bridge
[           resources] Started resource ring
[ citizen-server-impl] Couldn't find resource category [EUP].
[    c-scripting-core] Creating script environments for sqz_carkeys
[           resources] Started resource sqz_carkeys
[    c-scripting-core] Creating script environments for sqz_rental
[           resources] Started resource sqz_rental
[    c-scripting-core] Creating script environments for esx-npwd
[           resources] Started resource esx-npwd
[    c-scripting-core] Creating script environments for esx-radio
[           resources] Started resource esx-radio
[    c-scripting-core] Creating script environments for screenshot-basic
[           resources] Started resource screenshot-basic
[    c-scripting-core] Creating script environments for pma-voice
[           resources] Started resource pma-voice
[    c-scripting-core] Creating script environments for npwd
[           resources] Started resource npwd
[    c-scripting-core] Creating script environments for npwd_services
[           resources] Started resource npwd_services
[                 cmd] Argument count mismatch (passed 3, wanted 2)
[      script:oxmysql] [10.3.39-MariaDB-0+deb10u1] Database server connection established!
[ citizen-server-impl]         fff                          
[ citizen-server-impl]   cccc ff   xx  xx     rr rr    eee  
[ citizen-server-impl] cc     ffff   xx       rrr  r ee   e 
[ citizen-server-impl] cc     ff     xx   ... rr     eeeee  
[ citizen-server-impl]  ccccc ff   xx  xx ... rr      eeeee 
[ citizen-server-impl]                                      
[ citizen-server-impl] Authenticated with cfx.re Nucleus: https://bennis-channel-v8b8qk.users.cfx.re/
[       script:ox_lib] An update is available for ox_lib (current version: 3.12.0)
[       script:ox_lib] https://github.com/overextended/ox_lib/releases/tag/v3.16.2
[  script:es_extended] [INFO] BPT FRAMEWORK INITIALIZED
[script:esx_uteknark1] [21:52:00] <esx_uteknark1> Seed item in configuration (coke_seed) found in ESX: Good!
[script:esx_uteknark1] [21:52:00] <esx_uteknark1> Product item in configuration (coke) found in ESX: Good!
[script:esx_uteknark1] [21:52:01] <esx_uteknark1> Uteknark loaded 0 plants
[ script:ox_inventory] [info] Inventory has loaded 262 items
[ script:esx_property] [INFO] Adding last_property column to users table
[ script:esx_property] [INFO] Adding Property into datastore table
[ script:esx_property] [INFO] Adding Property into datastore_data table
> txaReportResources
[      script:monitor] [txAdmin] Sending resources list to txAdmin.
[  script:es_extended] Connecting: benjaminmani28
[      script:oxmysql] Error: es_extended was unable to execute a query!
[      script:oxmysql] Query: INSERT INTO `users` SET `accounts` = ?, `identifier` = ?, `group` = ?, `firstname` = ?, `lastname` = ?, `dateofbirth` = ?, `sex` = ?, `height` = ?
[      script:oxmysql] Field 'crafting_level' doesn't have a default value

**Comment by bitpredator** [comment]
Do you use TxAdmin ?

**Comment by Bennii9595** [comment]
yes

**Comment by bitpredator** [comment]
> yes

I understand, do you mind trying to start the server with the start.bat file that you find in server-data and give me news, also I inform you that I have released an update regarding esx_dmvschool.

**Comment by Bennii9595** [comment]
i use tube hosting i dont know how to use bat on that

**Comment by bitpredator** [comment]
> i use tube hosting i dont know how to use bat on that

Does your host have the ability to access the service via remote desktop?

**Comment by Bennii9595** [comment]
yes with terminus

**Comment by Bennii9595** [comment]
but its linux

**Comment by Bennii9595** [comment]
everything worli just get one problem  script:oxmysql] Error: es_extended was unable to execute a query!
[      script:oxmysql] Query: INSERT INTO `users` SET `accounts` = ?, `identifier` = ?, `group` = ?, `firstname` = ?, `lastname` = ?, `dateofbirth` = ?, `sex` = ?, `height` = ?
[      script:oxmysql] Field 'crafting_level' doesn't have a default value
> txaReportResources

**Comment by bitpredator** [comment]
If you are present in my discord server, would you mind showing me the installation procedure you carry out, I use zap-hosting or oracle with a windows operating system

**Comment by Bennii9595** [comment]
yes i cn show you so its better to use windows?

**Comment by bitpredator** [comment]
yes, I prefer to use windows, the RDP (virtualized remote desktop) function is very convenient.
![win_rdc](https://github.com/bitpredator/empiretown/assets/67551273/0133aa40-4e86-41c6-bf66-33ef185cbeed)
![Microsoft-Remote-Desktop-Preview-5-1024x576](https://github.com/bitpredator/empiretown/assets/67551273/ccdb3b47-84f9-471c-a23b-4300f4e1fffd)
it's like having a second dedicated monitor
