### ISSUE TITLE
Prova di contatto

### ISSUE THREAD

**Issue by Damidjo** [bitpredator/empiretown#75]
Ciao, piacere Giovanni, avrei bisogno di scambiare due chiacchiere, mi scuso per l'utilizzo scorretto, ma ci sarebbe modo di contattarti?

**Comment by bitpredator** [comment]
> Ciao, piacere Giovanni, avrei bisogno di scambiare due chiacchiere, mi scuso per l'utilizzo scorretto, ma ci sarebbe modo di contattarti?


Hello @Damidjo, you can use without any problem this request you opened for whatever you need :) .

Greetings bitpredator

**Comment by bitpredator** [comment]
No reply from the author, for this reason it will be closed as resolved.
